_wandb:
    value:
        cli_version: 0.24.0
        e:
            m66i7nofc9yag75a6xwvz8jeitmirj77:
                args:
                    - --trainval_artifact
                    - trainval_data.csv:latest
                    - --val_size
                    - "0.2"
                    - --random_seed
                    - "42"
                    - --stratify_by
                    - neighbourhood_group
                    - --rf_config
                    - /workspace/Project-Build-an-ML-Pipeline-Starter/rf_config.json
                    - --max_tfidf_features
                    - "5"
                    - --output_artifact
                    - random_forest_model
                codePath: src/train_random_forest/run.py
                codePathLocal: run.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "2160158191616"
                        used: "537741934592"
                email: niepce25@gmail.com
                executable: /home/student/miniconda3/envs/mlflow-0308d6078014cc87535b8e3327c959fc9c2e4a55/bin/python
                git:
                    commit: 4bfb05b6ee52f454021084453e269de66e9fb5fa
                    remote: https://github.com/niepce-hub/Project-Build-an-ML-Pipeline-Starter
                host: 77dc9dde389e762271efddce939274f8192484d9-f965795d6-z87pg
                memory:
                    total: "135077654528"
                os: Linux-6.6.97+-x86_64-with-glibc2.31
                program: /workspace/Project-Build-an-ML-Pipeline-Starter/src/train_random_forest/run.py
                python: CPython 3.13.0
                root: /workspace/Project-Build-an-ML-Pipeline-Starter/src/train_random_forest
                startedAt: "2026-08-05T08:04:37.627787Z"
                writerId: m66i7nofc9yag75a6xwvz8jeitmirj77
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.13.0
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
criterion:
    value: squared_error
max_depth:
    value: 15
max_features:
    value: 0.5
max_tfidf_features:
    value: 5
min_samples_leaf:
    value: 3
min_samples_split:
    value: 4
n_estimators:
    value: 100
n_jobs:
    value: -1
oob_score:
    value: true
output_artifact:
    value: random_forest_model
random_seed:
    value: 42
rf_config:
    value: /workspace/Project-Build-an-ML-Pipeline-Starter/rf_config.json
stratify_by:
    value: neighbourhood_group
trainval_artifact:
    value: trainval_data.csv:latest
val_size:
    value: 0.2
